//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminKiosco.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Subscripcion = new HashSet<Subscripcion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int KioscoId { get; set; }
        public string Domicilio { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual Kiosco Kiosco { get; set; }
        public virtual ICollection<Subscripcion> Subscripcion { get; set; }
    }
}
