//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminKiosco.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistribuidorKiosco
    {
        public int Id { get; set; }
        public string NroClienteDistribuidor { get; set; }
        public int KioscoId { get; set; }
        public int DistribuidorId { get; set; }
        public int DistribuidorCuentaId { get; set; }
    
        public virtual Distribuidor Distribuidor { get; set; }
        public virtual DistribuidorCuenta DistribuidorCuenta { get; set; }
        public virtual Kiosco Kiosco { get; set; }
    }
}
