//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminKiosco.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistribuidorCuenta
    {
        public DistribuidorCuenta()
        {
            this.DistribuidorKiosco = new HashSet<DistribuidorKiosco>();
        }
    
        public int Id { get; set; }
        public int DistribuidorId { get; set; }
        public string CBU { get; set; }
        public string Banco { get; set; }
    
        public virtual Distribuidor Distribuidor { get; set; }
        public virtual ICollection<DistribuidorKiosco> DistribuidorKiosco { get; set; }
    }
}
