//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminKiosco.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editorial
    {
        public Editorial()
        {
            this.Editorial1 = new HashSet<Editorial>();
            this.Publicacion = new HashSet<Publicacion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int DistribuidorId { get; set; }
        public Nullable<int> EditorialPadreId { get; set; }
    
        public virtual Distribuidor Distribuidor { get; set; }
        public virtual ICollection<Editorial> Editorial1 { get; set; }
        public virtual Editorial Editorial2 { get; set; }
        public virtual ICollection<Publicacion> Publicacion { get; set; }
    }
}
