//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminKiosco.Entities
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class KioscoUsuario
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public System.Guid UsuarioId { get; set; }
        public int KioscoId { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Kiosco Kiosco { get; set; }
    }
}
