//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminKiosco.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiosco
    {
        public Kiosco()
        {
            this.Cliente = new HashSet<Cliente>();
            this.DistribuidorKiosco = new HashSet<DistribuidorKiosco>();
            this.KioscoUsuario = new HashSet<KioscoUsuario>();
            this.MovimientosDiarios = new HashSet<MovimientosDiarios>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<DistribuidorKiosco> DistribuidorKiosco { get; set; }
        public virtual ICollection<KioscoUsuario> KioscoUsuario { get; set; }
        public virtual ICollection<MovimientosDiarios> MovimientosDiarios { get; set; }
    }
}
