//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminKiosco.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioVenta
    {
        public int Id { get; set; }
        public double Precio { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int PublicacionId { get; set; }
        public double PrecioFeriado { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
    }
}
