//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminKiosco.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public Publicacion()
        {
            this.CostoPublicacion = new HashSet<CostoPublicacion>();
            this.MovimientosDiarios = new HashSet<MovimientosDiarios>();
            this.PrecioVenta = new HashSet<PrecioVenta>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int DistribuidorId { get; set; }
        public string CodigoBarras { get; set; }
        public int EditorialId { get; set; }
        public bool TieneCupon { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public System.DateTime FechaUltimaSalida { get; set; }
        public int FrecuenciaEnDias { get; set; }
        public int PeriodicidadEnDias { get; set; }
    
        public virtual ICollection<CostoPublicacion> CostoPublicacion { get; set; }
        public virtual Distribuidor Distribuidor { get; set; }
        public virtual Editorial Editorial { get; set; }
        public virtual ICollection<MovimientosDiarios> MovimientosDiarios { get; set; }
        public virtual ICollection<PrecioVenta> PrecioVenta { get; set; }
    }
}
