//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminKiosco.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public Publicacion()
        {
            this.Promocion = new HashSet<Promocion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int DistribuidorId { get; set; }
        public int TipoPublicacionId { get; set; }
    
        public virtual Distribuidor Distribuidor { get; set; }
        public virtual ICollection<Promocion> Promocion { get; set; }
        public virtual TipoPublicacion TipoPublicacion { get; set; }
    }
}
